### ISSUE TITLE
Milestone 1: Filling summary of work performed by each team member

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#329]
### Description:

For the Milestone 1 group report, each member should list of their works which have done in milestone 1. It is mandatory for the all members.

### Who to do:

- [x] Berat Damar
- [x] Erdinç Günaydın
- [x] Yusuf Bayındır
- [x] Umut Deniz Şener
- [ ] Oğuzhan Tok
- [x] Elif Tokluoğlu
- [ ] Fatih Akgöz
- [x] Halil Salih Orhan
- [x] Miraç Batuhan Malazgirt
- [x] Melih Aktaş
- [x] Yiğit Can Özkaya

### Deadline of the Issue

04.11.2022 - Friday - 22.15

### Reviewer

@mbatuhan-malazgirt  and @yigit-can-ozkaya 

### Deadline for the Review

04.11.2022 - Friday - 22.45

**Comment by umutdenizsenerr** [comment]
I have filled my part. You can view at https://github.com/bounswe/bounswe2022group4/commit/bc0dcfd1dc190c7b094b75ea3e2e5d6596e7fab3.

**Comment by yigit-can-ozkaya** [comment]
I've filled my part too. After all of the team has complete their task. I'll close this issue.

**Comment by halilsalihorhan** [comment]
filled my part

**Comment by mbatuhan-malazgirt** [comment]
I have filled my part, I marked myself as complete.

**Comment by eliftoklu** [comment]
I have filled my part, I marked myself as complete
