### ISSUE TITLE
Milestone 1: Filling of responsibilities that are assigned to each member

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#330]
### Description:

For the Milestone 1 group report, each member should list of their responsibilities which have assigned in milestone 1. It is mandatory for the all members. It should be filled immediately. 

### Who to do:

- [x] Berat Damar
- [x] Erdinç Günaydın
- [ ] Yusuf Bayındır
- [x] Umut Deniz Şener
- [ ] Oğuzhan Tok
- [x] Elif Tokluoğlu
- [ ] Fatih Akgöz
- [x] Halil Salih Orhan
- [x] Miraç Batuhan Malazgirt
- [x] Melih Aktaş
- [x] Yiğit Can Özkaya

### Deadline of the Issue

04.11.2022 - Friday - 22.15

### Reviewer

@BeratDamar and @MercerFrey 

### Deadline for the Review

04.11.2022 - Friday - 22.45

**Comment by umutdenizsenerr** [comment]
I have filled my part. You can view at https://github.com/bounswe/bounswe2022group4/commit/77a8903fe9844f55cf3e2b54487a8e9cd556e47d.

**Comment by yigit-can-ozkaya** [comment]
I have filled my personal part. I also renew the requirements for this milestone as a group member.

**Comment by halilsalihorhan** [comment]
filled my part

**Comment by mbatuhan-malazgirt** [comment]
I have filled my part, I marked myself as complete.

**Comment by eliftoklu** [comment]
I have filled my part, I marked myself as complete.

**Comment by BeratDamar** [comment]
I have filled my part and I signed  myself.
