### ISSUE TITLE
Milestone 1: Listing of status of deliverables

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#331]
### Description:

I will list and provide information about the status of the deliverables for the Milestone 1. I will comment under this issue the work which have done. After comment, reviewers will the confirm or indicate problems work which have done.

### What to list:

- [x] Software Requirements Specification
- [x] Software Design (UML)
- [x] Scenarios and Mockups
- [x] Project Plan
- [x] Individual Contribution Reports
- [x] Customer Milestone 1 Group Review
- [x] Demo Presentation

### Deadline of the Issue

04.11.2022 - Friday - 22.15

### Reviewer

@BeratDamar and @MercerFrey 

### Deadline for the Review

04.11.2022 - Friday - 22.45

**Comment by BeratDamar** [comment]
Since all tasks were completed, I close issue. Thanks for your contributions.
